


Skelelang.i18n.addl10n({
    en: {
        "usernameMail_lbl": "Username or email",
        "password_lbl": "Password",
        "passwordShadowConfirm_lbl": "Repeat password",
        "oldPassword_lbl": "Old password",
        "newPassword_lbl": "New password",
        "newPasswordShadowConfirm_lbl": "New password confirm",
        "username_lbl": "Username",
        "roles_lbl": "Roles",
        "delete_lbl": "Delete?",
        "userEmail_lbl": "Email",
        "cellular_lbl": "Mobile phone",
        "old_lbl": "Old",
        "new_lbl": "New",
        "confirm_lbl": "Confirm",
        "accessLevel_lbl": "Access Level",
        "optionalData_lbl": "Other data [optional]",
        "phone_lbl": "Telephone",
        "role_lbl": "Role",
        "data_lbl": "Data:",
        "title_lbl": "Title",
        "code_lbl": "Slug",
        "content_lbl": "Text",
        "date_lbl": "Date",
        "mainImage_lbl": "Main image",
        "nameUrl_lbl": "Url name",
        "introText_lbl": "Intro text",
        "firstNameLastName": "First name and last name",
        "firstName_lbl": "First name",
        "lastName_lbl": "Last name",
        "clipboard_lbl": "Clipboard",
        "fiscalCode_lbl": "Fiscal code",
        "birthPlace_lbl": "Place of birth",
        "birthDay_lbl": "Birth day",
        "city_lbl": "City",
        "address_lbl": "Address",
        "zipCode_lbl": "Zip code",
        "province_lbl": "Province",
        "all_lbl": "All",
        "duration_lbl": "Duration",
        "name_lbl": "Name",
        "cardTimes_lbl": "Subscription",
        "notFound_lbl": "Not found",
        "rollbackEntry_lbl": "Undo access?",
        "dateTime_lbl": "Date and time",
        "price_lbl": "Price",
        "initialValue_lbl": "Initial value",
        "width_lbl": "Width",
        "height_lbl": "Height",
        "pageOptions_lbl": "Page options",
        "csen_lbl": "CSEN number",
        "pageWidth_lbl": "Width",
        "pageHeight_lbl": "Height",
        "labelOptions_lbl": "Label options",
        "labelWidth_lbl": "Width",
        "labelHeight_lbl": "Height",
        "pageMargins_lbl": "Margins",
        "pageLeft_lbl": "Left",
        "pageRight_lbl": "Right",
        "pageTop_lbl": "Top",
        "pageBottom_lbl": "Bottom",
        "codeOptions_lbl": "Codes options",
        "page_lbl": "Page",
        "codesText_lbl": "Text above codes",
        "paperFormat_lbl": "Page format",
        "reloadedImage_lbl": "(image loaded from db)",
        "profileImage_lbl": "Profile image",
        "imageTitle_lbl": "Image title",
        "altText_lbl": "Alternative text:",
        "videoUrl_lbl": "Video URL:",
        "videoAddress_lbl": "Video address",
        "preview_lbl": "Preview:",
        "telephone_lbl": "Telephone",
        "UILang_lbl": "UI language:",
        "contentsLang_lbl": "Lingua contenuti:",
        "languages_lbl": "langs: ",
        "social_lbl": "social:",
        "status_lbl": "status:",
        "connected_lbl": "connected",
        "connecting_lbl": "connecting...",
        "failed_lbl": "connection failed",
        "waiting_lbl": "waiting for connection",
        "offline_lbl": "connection interrupted",
        "published_lbl": "Published",
        "publish_lbl": "Publish options",
        "menuItem_lbl": "Menu item",
        "section_lbl": "Section",
        "menu_lbl": "Assign to menu",
        "menuName_lbl": "Menu item name",
        "description_lbl": "Description",
        "usersManagement_lbl": "Users management",
        "allowUsersRead_lbl": "Read",
        "allowUsersCreate_lbl": "Create",
        "allowUsersUpdate_lbl": "Update",
        "allowUsersDelete_lbl": "Delete",
        "rolesManagement_lbl": "Roles management",
        "allowRolesRead_lbl": "Read",
        "allowRolesCreate_lbl": "Create",
        "allowRolesUpdate_lbl": "Update",
        "allowRolesDelete_lbl": "Delete",
        "pagesManagement_lbl": "Pages",
        "allowPagesRead_lbl": "Read",
        "allowPagesCreate_lbl": "Create",
        "allowPagesUpdate_lbl": "Update",
        "allowPagesDelete_lbl": "Delete",
        "sectionsManagement_lbl": "Sections",
        "allowSectionsRead_lbl": "Read",
        "allowSectionsCreate_lbl": "Create",
        "allowSectionsUpdate_lbl": "Update",
        "allowSectionsDelete_lbl": "Delete",
        "menusManagement_lbl": "Pages",
        "allowMenusRead_lbl": "Read",
        "allowMenusCreate_lbl": "Create",
        "allowMenusUpdate_lbl": "Update",
        "allowMenusDelete_lbl": "Delete",
        "panelAccess_lbl": "Panel access",
        "allowPanelAccess_lbl": "Allow",
        "configManagement_lbl": "Configuration options",
        "debugManagement_lbl": "Debug tools",
        "allowConfigRead_lbl": "Read",
        "allowConfigUpdate_lbl": "Update",
        "allowDebugRead_lbl": "Read",
        "allowDebugUpdate_lbl": "Update",
        "mainFunctions_lbl": "Main functions",
        "actions_lbl": "Actions",
        "changePasswordTitle_lbl": "Change password for",
        "undoDelete_lbl": "Confirm in",
        "none_lbl": "(none)",
        "yes_lbl": "Yes",
        "no_lbl": "No",
        "enabledLanguages_lbl": "UI languages enabled",
        "it_lbl": "Italian",
        "en_lbl": "English",
        "fr_lbl": "French",
        "publicSettingsIntroText_lbl": "This is the application's general public configuration.<br><b>Attention</b> editing this configuration may change the application's behavior.",
        "policyBar_lbl": "Policy bar",
        "displayAlways_lbl": "Display always",
        "applicationDetails_lbl": "Application details",
        "appName_lbl": "Application name",
        "appDetail_lbl": "Application detail",
        "siteName_lbl": "Website name",
        "siteDetail_lbl": "Website detail",
        "mainEmail_lbl": "Main e-mail",
        "webmasterEmail_lbl": "Webmaster's e-mail",
        "version_lbl": "Version",
        "debugTitle_lbl": "Debug",
        "debug_lbl": "Debug mode",
        "authorDetails_lbl": "Author details",
        "authorName_lbl": "Name",
        "authorWebsite_lbl": "Website",
        "authorWebsiteText_lbl": "Website text",
        "pathsDetails_lbl": "Paths details",
        "defaultLandingPage_lbl": "Landing page",
        "loginPaths_lbl": "Login paths",
        "loginDefaultLoginPath_lbl": "Default login",
        "loginDefaultLogoutPath_lbl": "Default logout",
        "loginDefaultRedirectPath_lbl": "Login redirect",
        "loginDefaultFailPath_lbl": "Login failed redirect",
        "animations_lbl": "Animations",
        "animationsDuration_lbl": "Durations",
        "animationsScrollTop_lbl": "Scroll to top",
        "animationsScrollBottom_lbl": "Scroll to bottom",
        "animationsScrollError_lbl": "Scroll to error",
        "animationsOnRendered_lbl": "After rendering",
        "langEnableIt_lbl": "Italian",
        "langEnableEn_lbl": "English",
        "lsPolicyBarDisplayAlways_lbl": "Always show",
        "consoleLogger_lbl": "Console logger",
        "profileRoles_lbl": "Roles",
        "profileName_lbl": "Real name",
        "profileTelephone_lbl": "Telephone",
        "controlPanel_lbl": "Control panel",
        "contentManagement_lbl": "content management",
        "aclManagement": "User and roles management",
        "configDebugManagement_lbl": "Configuration and debug management",
        "placeholder_lbl": "Placeholder",
        "placeholderItem_lbl": "Assign to placeholder",
        "availableTemplates_lbl": "Template",
        "templatePositions_lbl": "Available positions",
        "menuIcon_lbl": "Icon",
        "langDefault_lbl": "Default language",
        "staticFilesPath_lbl": "Static files path",
        "pathDetailsInfo_lbl": "The following path are required only to override the default ones",
        "defaultLangInfo_lbl": "If enabled the system will check if user browser's language is supported, otherwise will use the default one.<br>This option is ignored when a specific language is included in the URL",
        "tryUserLangFirst_lbl": "Check user language support",
        "deleteConfirmation_lbl": "Delete confirmation",
        "enableFrontEndLangbar_lbl": "Enable language bar in the website",
        "noAssociatedUser_lbl": "No associated user",
        "loadMore_lbl": "Load more...",
        "totalNumber_lbl": "Total number:",
        "undefined_lbl": '(Undefined)',

        "editorBackgroundStyle_lbl": "Switch editor's background",
        "boldStyle_lbl": "Bold",
        "underlineStyle_lbl": "Underline",
        "italicStyle_lbl": "Italic",
        "fontHeight_lbl": "Font height",

        "administrator_role": "Administrator",
        "administratorLong_role": "System Administrator",
        "editor_role": "Editor",
        "superuser_role": "Super user",
        "superuserLong_role": "Superutente dal divino potere",

        "dataTable_search": "Search in table",
        "dataTable_lengthMenu": "Show _MENU_ rows",

        "imageUploadTitle_modal": "Image upload",
        "videoEmbeed_modal": "Embeed video",

        "welcome_msg": "Welcome",
        "version": "Version"
    }
});
