


Skelelang.i18n.addl10n({
    en: {
        "whatYouNeed_text": "what do you need?",
        "adminTools_text": "Administrative tools",
        "workInProgress_text": "This page is a work in progress...",
        "404Title_text": "404 Not found!",
        "404Subtitle_text": "This is not the page you are looking for...",
        "404Detail_text": "Sorry, this page does not exist!<br>You are here beacause one of the followings<br><br> <ul class=\"\"><li>A wrong url</li><li>An outdated bookmark</li><li>A subspatial interference caused by a vehicle with warp drive</li></ul>",
        "unpublishedTitle_text": "403 Unpublished!",
        "unpublishedSubtitle_text": "This page has been unpublished...",
        "unpublishedDetail_text": "Sorry, this page is not visible<br>You are here because<br>an administrator has removed the page from the published list<br><br>Normally this is a temporary situation...",
        "unsupportedLangTitle_text": "Unsupported language",
        "unsupportedLangSubtitle_text": "Translation not found",
        "unsupportedLangDetail_text": "You requested the page in an unavailable or inexistent language<br>Please select a language from the available ones...",
        "currentLangNewsWarning_text": "ATTENTION:<br>This page will show only the news in the currently selected language",
        "superUserRole_text": "<b>The super user powers</b> <ul><li>invincibility - always gain access to every section of the application. Always pass any security check</li><li>indestructibility - this role is not editable nor deletable</li><li>eternal persistence - there must always be at least one super user otherwise some parts of the application may result inaccessible</li></ul><i>Phenomenal cosmic powers... In a tiny memory array...</i>",
        "contentDescription_text": "Defines the permissions for contents, sections and menus management<br><b>Attention:</b> edit these permissions can make some parts of the website unavailable to users",
        "aclDescription_text": "Defines the permissions for users and roles<br>independently from the setted permissions, the data relatives to the current user and its roles will always be available in reading",
        "mainFunctionsDescription_text": "<b>Attention:</b> editing these permissions can exclude the users group from the use of the administration panel",
        "subscriptionsDataDescription_text": "Defines the permissions for membership and subscriptions management",

        "usersListTitle_text": "Users management",
        "userTypes_text": "TYPE OF USERS<br><br><ul style=\"list-style: none;\"><li><b>Administrator</b> -> general management</li><li><b>Editor</b> -> update of website's texts</li></ul>",
        "createUser_text": "New User Creation",
        "updateUser_text": "User Update:",
        "rolesListTitle_text": "Roles management",
        "roles_text": "This page allows to create or delete roles",
        "createRole_text": "Create role",
        "updateRole_text": "Update role",
        "pagesListTitle_text": "Pages management",
        "pagesList_text": "PAGES TEXTS EDITING<br><br><p>Once logged the page's texts can also be updated on the website directly by clicking on text you want to edit</p>",
        "createPage_text": "Create creation",
        "updatePage_text": "Update page",
        "sectionsListTitle_text": "Sections management",
        "createSection_text": "Create section",
        "updateSection_text": "Update section",
        "menusListTitle_text": "Menu management",
        "createMenu_text": "Create menu",
        "updateMenu_text": "Update menu",
        "newsListTitle_text": "News management",
        "createNews_text": "News creation",
        "updateNews_text": "Update news",
        "newsTitle_text": "Latest news",
        "applicationButtons_text": "Access control application",
        "websiteButtons_text": "Website and content",
        "aclButtons_text": "Users and roles",
        "designedBy_text": "Designed by",
        "for_text": "for",
        "unauthorized_text": "You are not authorized to see this resource!",
        "configButtons_text": "App configuration",
        "updateSetting_text": "Update configuration",
        "updateApplicationData_text": "Update application data"
    }
});
