


Skelelang.i18n.addl10n({
    it: {
        "usernameMail_lbl": "Nome utente o mail",
        "password_lbl": "Password",
        "passwordShadowConfirm_lbl": "Conferma password",
        "oldPassword_lbl": "Vecchia password",
        "newPassword_lbl": "Nuova password",
        "newPasswordShadowConfirm_lbl": "Conferma nuova password",
        "username_lbl": "Nome utente",
        "roles_lbl": "Ruoli",
        "delete_lbl": "Elimina?",
        "userEmail_lbl": "Email",
        "associatedEmails_lbl": "E-mail associate",
        "cellular_lbl": "Cellulare",
        "old_lbl": "Vecchia",
        "new_lbl": "Nuova",
        "confirm_lbl": "Conferma",
        "accessLevel_lbl": "Livello di Accesso",
        "optionalData_lbl": "Altri dati [opzionali]",
        "phone_lbl": "Telefono",
        "role_lbl": "Ruolo",
        "data_lbl": "Dati:",
        "title_lbl": "Titolo",
        "code_lbl": "Codice",
        "content_lbl": "Testo",
        "date_lbl": "Data",
        "mainImage_lbl": "Foto principale",
        "nameUrl_lbl": "Nome Url",
        "introText_lbl": "Testo introduttivo",
        "firstNameLastName": "Nome e cognome",
        "firstName_lbl": "Nome",
        "lastName_lbl": "Cognome",
        "clipboard_lbl": "Appunti",
        "fiscalCode_lbl": "Codice fiscale",
        "birthPlace_lbl": "Luogo di nascita",
        "birthDay_lbl": "Data di nascita",
        "city_lbl": "Città",
        "address_lbl": "indirizzo",
        "zipCode_lbl": "C.a.p.",
        "province_lbl": "Provincia",
        "all_lbl": "Tutte",
        "duration_lbl": "Durata",
        "name_lbl": "Nome",
        "cardTimes_lbl": "Abbonamento",
        "notFound_lbl": "Inesistente",
        "rollbackEntry_lbl": "Annulla ingresso?",
        "dateTime_lbl": "Data e ora",
        "price_lbl": "Prezzo",
        "initialValue_lbl": "Valore iniziale",
        "width_lbl": "Larghezza",
        "height_lbl": "Altezza",
        "pageOptions_lbl": "Opzioni pagina",
        "csen_lbl": "N° tessera CSEN",
        "pageWidth_lbl": "Larghezza",
        "pageHeight_lbl": "Altezza",
        "labelOptions_lbl": "Opzioni etichetta",
        "labelWidth_lbl": "Larghezza",
        "labelHeight_lbl": "Altezza",
        "pageMargins_lbl": "Margini",
        "pageLeft_lbl": "Sinistro",
        "pageRight_lbl": "Destro",
        "pageTop_lbl": "Superiore",
        "pageBottom_lbl": "Inferiore",
        "codeOptions_lbl": "Opzioni codici",
        "page_lbl": "Pagina",
        "codesText_lbl": "Testo sopra i codici",
        "paperFormat_lbl": "Formato pagina",
        "reloadedImage_lbl": "(immagine caricata dal database)",
        "profileImage_lbl": "Immagine profilo",
        "imageTitle_lbl": "Titolo immagine",
        "altText_lbl": "Testo alternativo:",
        "videoUrl_lbl": "URL video:",
        "videoAddress_lbl": "Indirizzo del video",
        "preview_lbl": "Anteprima:",
        "telephone_lbl": "Telefono",
        "UILang_lbl": "Lingua interfaccia:",
        "contentsLang_lbl": "Lingua contenuti:",
        "languages_lbl": "lingue: ",
        "social_lbl": "social:",
        "status_lbl": "stato:",
        "connected_lbl": "connesso",
        "connecting_lbl": "in connessione...",
        "failed_lbl": "connessione fallita",
        "waiting_lbl": "in attesa di riconnessione",
        "offline_lbl": "connessione interrotta",
        "published_lbl": "Pubblicato",
        "publish_lbl": "Pubblicazione",
        "menuItem_lbl": "Voce di menu",
        "section_lbl": "Sezione",
        "menu_lbl": "Assegna al menu",
        "menuName_lbl": "Nome voce menu",
        "description_lbl": "Descrizione",
        "usersManagement_lbl": "Gestione utenti",
        "allowUsersRead_lbl": "Lettura",
        "allowUsersCreate_lbl": "Creazione",
        "allowUsersUpdate_lbl": "Aggiornamento",
        "allowUsersDelete_lbl": "Cancellazione",
        "rolesManagement_lbl": "Gestione Ruoli",
        "allowRolesRead_lbl": "Lettura",
        "allowRolesCreate_lbl": "Creazione",
        "allowRolesUpdate_lbl": "Aggiornamento",
        "allowRolesDelete_lbl": "Cancellazione",
        "pagesManagement_lbl": "Gestione pagine",
        "allowPagesRead_lbl": "Lettura",
        "allowPagesCreate_lbl": "Creazione",
        "allowPagesUpdate_lbl": "Aggiornamento",
        "allowPagesDelete_lbl": "Cancellazione",
        "sectionsManagement_lbl": "Sections",
        "allowSectionsRead_lbl": "Lettura",
        "allowSectionsCreate_lbl": "Creazione",
        "allowSectionsUpdate_lbl": "Aggiornamento",
        "allowSectionsDelete_lbl": "Cancellazione",
        "menusManagement_lbl": "Pages",
        "allowMenusRead_lbl": "Lettura",
        "allowMenusCreate_lbl": "Creazione",
        "allowMenusUpdate_lbl": "Aggiornamento",
        "allowMenusDelete_lbl": "Cancellazione",
        "panelAccess_lbl": "Accesso al pannello",
        "allowPanelAccess_lbl": "Permetti",
        "configManagement_lbl": "Opzioni di configurazione",
        "debugManagement_lbl": "Strumenti di debug",
        "allowConfigRead_lbl": "Lettura",
        "allowConfigUpdate_lbl": "Aggiornamento",
        "allowDebugRead_lbl": "Lettura",
        "allowDebugUpdate_lbl": "Aggiornamento",
        "mainFunctions_lbl": "Funzioni principali",
        "actions_lbl": "Azioni",
        "changePasswordTitle_lbl": "Cambio password per",
        "undoDelete_lbl": "Conferma entro",
        "none_lbl": "(nessuno/a)",
        "yes_lbl": "Sì",
        "no_lbl": "No",
        "enabledLanguages_lbl": "Lingue UI abilitate",
        "it_lbl": "Italiano",
        "en_lbl": "Inglese",
        "fr_lbl": "Francese",
        "publicSettingsIntroText_lbl": "Questa è la configurazione pubblica generale dell'applicazione.<br><b>Attenzione</b> le modifiche possono alterare il comportamento dell'applicazione.",
        "policyBar_lbl": "Barra policy",
        "displayAlways_lbl": "Mostra sempre",
        "applicationDetails_lbl": "Dettagli applicazione",
        "appName_lbl": "Nome applicazione",
        "appDetail_lbl": "Dettaglio applicazione",
        "siteName_lbl": "Nome sito",
        "siteDetail_lbl": "Dettagli sito",
        "mainEmail_lbl": "E-mail principale",
        "webmasterEmail_lbl": "E-mail webmaster",
        "version_lbl": "Versione",
        "debugTitle_lbl": "Debug",
        "debug_lbl": "Modalità debug",
        "authorDetails_lbl": "Dettagli autore",
        "authorName_lbl": "Nome",
        "authorWebsite_lbl": "Sito web",
        "authorWebsiteText_lbl": "Testo sito web",
        "pathsDetails_lbl": "Dettagli percorsi",
        "defaultLandingPage_lbl": "Home page predefinita",
        "loginPaths_lbl": "Percorsi di login",
        "loginDefaultLoginPath_lbl": "Login predefinito",
        "loginDefaultLogoutPath_lbl": "Logout predefinito",
        "loginDefaultRedirectPath_lbl": "Redirect al login",
        "loginDefaultFailPath_lbl": "Redirect errore di login",
        "animations_lbl": "Animazioni",
        "animationsDuration_lbl": "Durata animazioni",
        "animationsScrollTop_lbl": "Scroll in alto",
        "animationsScrollBottom_lbl": "Scroll in basso",
        "animationsScrollError_lbl": "Scroll all'errore",
        "animationsOnRendered_lbl": "Al caricamento",
        "langEnableIt_lbl": "Italiano",
        "langEnableEn_lbl": "Inglese",
        "lsPolicyBarDisplayAlways_lbl": "Mostra sempre",
        "consoleLogger_lbl": "Console logger",
        "profileRoles_lbl": "Ruoli",
        "profileName_lbl": "Nome reale",
        "profileTelephone_lbl": "Telefono",
        "controlPanel_lbl": "Pannello di controllo",
        "contentManagement_lbl": "Gestione contenuti",
        "aclManagement_lbl": "Gestione Utenti e ruoli",
        "configDebugManagement_lbl": "Gestione configurazione e debug",
        "placeholder_lbl": "Segnaposto",
        "placeholderItem_lbl": "Assegna al segnaposto",
        "availableTemplates_lbl": "Template",
        "templatePositions_lbl": "Posizioni disponibili",
        "menuIcon_lbl": "Icona",
        "langDefault_lbl": "Lingua predefinita",
        "staticFilesPath_lbl": "Percorso files statici",
        "pathDetailsInfo_lbl": "I percorsi qui di seguito vanno specificati unicamente per fare l'override di quelli predefiniti",
        "defaultLangInfo_lbl": "Se attivo, il sistema verificherà se la lingua del browser dell'utente è supportata, in caso contrario utilizzerà quella di default.<br>Questa opzione viene ignorata quando una specifica lingua è inclusa nell'URL",
        "tryUserLangFirst_lbl": "Verifica supporto lingua utente",
        "deleteConfirmation_lbl": "Conferma eliminazione",
        "enableFrontEndLangbar_lbl": "Abilita la barra della lingua sul sito",
        "noAssociatedUser_lbl": "Nessun utente associato",
        "loadMore_lbl": "Carica altri...",
        "totalNumber_lbl": "Numero totale:",
        "undefined_lbl": "(Non definito)",
        "searchText_lbl": "da cercare...",
        "associatedPages_lbl": "Pagine associate",
        "time_lbl": "ora",
        "empty_lbl": "vuoto",
        "confirmAction_lbl": "<h4>Conferma azione</h4>",
        "timeMachine_lbl": "Time machine",
        "timeMachineUse_lbl": "Consenti utilizzo",
        "availableStates_lbl": "Stati disponibili",
        "currentState_lbl": "Stato corrente",

        "editorBackgroundStyle_lbl": "Alterna sfondo editor",
        "boldStyle_lbl": "Grassetto",
        "underlineStyle_lbl": "Sottolineato",
        "italicStyle_lbl": "Corsivo",
        "fontHeight_lbl": "Altezza carattere",

        "administrator_role": "Amministratore",
        "administratorLong_role": "Amministratore di Sistema",
        "editor_role": "Editore",
        "superuser_role": "Super utente",
        "superuserLong_role": "Superutente dal divino potere",

        "dataTable_search": "Cerca nella tabella",
        "dataTable_lengthMenu": "Mostra _MENU_ righe",

        "imageUploadTitle_modal": "Inserimento immagine",
        "videoEmbeed_modal": "Incorpora video",

        "welcome_msg": "Benvenuto",
        "version": "Versione"
    }
});
